N_NOTES = 12
N_DIATONIC_SCALE_NOTES = 7

SHARP_CHAR = "#"
FLAT_CHAR = "b"
DOUBLE_SHARP_CHARS = SHARP_CHAR * 2
DOUBLE_FLAT_CHARS = FLAT_CHAR * 2
MAJ_CHARS = ""
MIN_CHARS = "m"
HALFDIM_CHARS = "halfdim"
DIM_CHARS = "dim"
AUG_CHARS = "aug"

SHARP_SYMBOL = "♯"
FLAT_SYMBOL = "♭"
DOUBLE_SHARP_SYMBOL = "𝄪"
DOUBLE_FLAT_SYMBOL = "𝄫"
MAJ_SYMBOL = ""
MIN_SYMBOL = "m"
HALFDIM_SYMBOL = "ø"
DIM_SYMBOL = "°"
AUG_SYMBOL = "+"
